Repository Vishal-raj-1/Awesome-JavaScript-Projects, pull requests merged in 2021-04, with the labels that each got.

#773 Added Breakout! Game
  assets/GIFs/breakout.gif
  assets/Images/breakoutt.png
  assets/css/Breakout.css
  assets/js/Breakout.js
  assets/js/calculator.js
  public/Breakout.html
  public/TextToSpeech.html
  public/calculator.html
  script.js
Labels: gssoc'21, level2

#767 Created and Added fruit slicer app
  assets/GIFs/fruitSlicer.gif
  assets/Images/1.png
  assets/Images/10.png
  assets/Images/11.png
  assets/Images/12.png
  assets/Images/13.png
  assets/Images/14.png
  assets/Images/15.png
  assets/Images/16.png
  assets/Images/17.png
  assets/Images/2.png
  assets/Images/3.png
  assets/Images/4.png
  assets/Images/5.png
  assets/Images/6.png
  assets/Images/7.png
  assets/Images/8.png
  assets/Images/9.png
  assets/Images/Gutsu_&_Truffles_Sidebar.png
  assets/Images/Sensei_Sidebar.png
  assets/Images/arrow.png
  assets/Images/bg.png
  assets/Images/bg2.png
  assets/Images/bg3.png
  assets/Images/bg4.png
  assets/Images/bg5.png
  assets/Images/bomb.png
  assets/Images/imgbin-fruit-ninja-best-candy-fruit-ninja-game-character-creatives-qZmr5sYHR0WEMEw7Vg2RvPhp4.jpg
  assets/Images/title.png
  assets/css/fruitSlicer.css
  assets/js/fruitSlicer.js
  assets/sounds/slicefruit.mp3
  assets/sounds/slicefruit.ogg
  assets/sounds/slicefruit.wav
  public/fruitSlicer.html
  script.js
Labels: gssoc'21, level3

#818 Added Falling Bullets Animation JS
  assets/GIFs/FallingBulletsAnimation.gif
  assets/css/FallingBulletsAnimation.css
  assets/js/FallingBulletsAnimation.js
  public/FallingBulletsAnimation.html
  script.js
Labels: gssoc'21, level2

#625 Adding Age calculator
  assets/Images/AgeCalculator.png
  assets/css/AgeCalculator.css
  assets/js/AgeCalculator.js
  public/AgeCalculator.html
  script.js
Labels: gssoc21, level2

#744 digital clock button bug
  assets/css/digitalClock.css
Labels: gssoc21, level0

#769 Random User Generator #339
  assets/GIFs/Random_User.gif
  assets/css/randomuser.css
  assets/js/randomuser.js
  public/Randomuser.html
  script.js
Labels: gssoc21, level2

#832 Adding project PlayBeats.
  assets/GIFs/playbeats.gif
  assets/css/playbeats-main.css
  assets/css/playbeats-reset.css
  assets/css/playbeats-semantic.min.css
  assets/js/playbeats-main.js
  public/Play-Beats.html
  script.js
Labels: gssoc21, level3

#703 Lyrics App
  assets/GIFs/lyricsApp.gif
  assets/css/lyricsApp.css
  assets/js/LyricsApp.js
  public/lyricsApp.html
  script.js
Labels: gssoc21, level2

#534 Added AND_OR_XOR_Converter
  assets/GIFs/AND_OR_XOR_Converter.gif
  assets/css/AND_OR_XOR_Converter.css
  assets/js/AND_OR_XOR_Converter.js
  public/AND_OR_XOR_Converter.html
  script.js
Labels: gssoc21, level2

#850 armstrong number added
  assets/GIFs/ArmstrongNumber.gif
  assets/css/ArmstrongNumber.css
  assets/js/ArmstrongNumber.js
  public/ArmstrongNumber.html
  script.js
Labels: gssoc21, level1

#472 Added Project Random Color Generator
  assets/Images/randomColorGenerator.png
  assets/css/randomColorGenerator.css
  assets/js/randomColorGenerator.js
  public/randomColorGenerator.html
  script.js
Labels: gssoc21, level2

#656 Balloon Firing Game issue #313
  assets/Images/balloonFiring.js.png
  assets/js/balloonFiring.js
  public/balloonFiring.html
  script.js
Labels: gssoc21, level2

#554 Added four files related to car avoidance game project (issue-368)
  assets/Images/carAvoidanceGame.png
  assets/css/carAvoidanceGame.css
  assets/js/carAvoidanceGame.js
  public/carAvoidanceGame.html
  script.js
Labels: gssoc21, level3

#568 2048 game
  assets/GIFs/2048.gif
  assets/css/2048.css
  assets/js/2048.js
  public/2048.html
  script.js
Labels: gssoc21, level2

#644 Added Expense Tracker and Weight converter
  assets/GIFs/ExpenseTracker.gif
  assets/GIFs/WeightConverter.gif
  assets/Images/Expense.svg
  assets/css/ExpenseTracker.css
  assets/css/WeightConverter.css
  assets/js/ExpenseTracker.js
  assets/js/WeightConverter.js
  public/ExpenseTracker.html
  public/WeightConverter.html
  script.js
Labels: gssoc21, level3

#676 added project Sequence-game
  assets/Images/sequence-game.PNG
  assets/css/sequence-game.css
  assets/js/Sequence-game.js
  assets/sounds/blue.mp3
  assets/sounds/green.mp3
  assets/sounds/red.mp3
  assets/sounds/wrong.mp3
  public/Sequence-game.html
  script.js
Labels: gssoc21, level2

#759 Adding Hospital registration form to Project collection
  assets/GIFs/registration_form.gif
  assets/css/registration_form.css
  assets/js/registration_form.js
  public/registration_form.html
  script.js
Labels: gssoc21, level1

#770 Make Speech Recognization
  assets/Images/speech-recognization.PNG
  assets/css/speech-recognization.css
  assets/js/speech-recognization.js
  public/speech-recognization.html
  script.js
Labels: gssoc21, level2

#765 Animation and Hover effect on Nav title
  assets/css/styles.css
  assets/js/scripts.js
  assets/typed.js/typed.js
  assets/typed.js/typed.min.js
  assets/typed.js/typed.min.js.map
  contact.html
  index.html
  package-lock.json
  projects.html
Labels: gssoc21, level1

#947 Made Drum-Kit responsive
  assets/css/drumKit.css
  public/drumKit.html
Labels: gssoc21, level1

#851 Created Dragon Game #1
  assets/Images/JavaScript Dragon Game.png
  assets/Images/bg.png
  assets/Images/dino.png
  assets/Images/dragon.png
  assets/css/dino-style.css
  assets/js/dino-script.js
  assets/sounds/gameover.mp3
  assets/sounds/music.mp3
  public/Dino game.html
  script.js
Labels: gssoc21, level3

#825 fixed incorrect sentence
  index.html
Labels: gssoc21, level0

#777 fixed bug and added features in local storage
  assets/css/localstorage.css
  assets/js/localstorage.js
  public/localstorage.html
Labels: gssoc21, level2

#699 http cats project
  assets/GIFs/httpcats.gif
  assets/Images/httpcat.ico
  assets/Images/welcomecat.jpg
  assets/css/httpcats.css
  assets/js/httpcats.js
  public/httpcats.html
  script.js
Labels: gssoc21, level2

#576 Added Moving Car Animation to the project list
  assets/GIFs/Animated_moving_car.gif
  assets/Images/Animated_moving_car/background.png
  assets/Images/Animated_moving_car/bus.png
  assets/Images/Animated_moving_car/tree.png
  assets/css/Animated_moving_car.css
  assets/js/Animated_moving_car.js
  public/Animated_moving_car.html
  script.js
Labels: gssoc21, level2

#366 Added visual Bubble Sort
  assets/GIFs/bubbleSort.gif
  assets/css/bubbleSort.css
  assets/js/bubbleSort.js
  public/bubbleSort.html
  script.js
Labels: gssoc21, level2

#524 Modified Drum kit and change its theme
  assets/css/drumKit.css
  assets/js/drumKit.js
  public/drumKit.html
Labels: gssoc21, level2

#809 Successfully added styles to the BMI Calculator page
  assets/GIFs/BMIcal.gif
  assets/Images/bathroom-scale.png
  assets/Images/bmi-bg.jpg
  assets/Images/diagnosis.png
  assets/css/BMICalculator.css
  assets/js/BMICalculator.js
  public/BMICalculator.html
Labels: assigned, gssoc21, level2

#520 Tertris Game
  assets/Images/TetrisGame.png
  assets/css/TetrisGame.css
  assets/js/TetrisGame.js
  public/TetrisGame.html
  script.js
Labels: assigned, gssoc21, level2

#561 added student marks calculator project...pls review it
  assets/Images/studentCalc.png
  assets/css/studentCalc.css
  assets/js/studentCalc.js
  public/studentCalc.html
  script.js
Labels: assigned, gssoc21, level2

#979 Updated Script.js file
  script.js
Labels: gssoc21, level0

#977 Added Interest Calculator.png
  assets/Images/InterestCalculator.png
Labels: gssoc21, level0

#751 New project addition : Rose | ( Mathematics )
  assets/Images/rose-mathematics/icon.png
  assets/css/rose-mathematics_css/rose-mathematics.min.css
  assets/css/rose-mathematics_css/rose-mathematics.min.css.map
  assets/css/rose-mathematics_css/rose-mathematics.scss
  assets/js/rose-mathematics_js/rose-mathematics.js
  assets/sounds/gameover.mp3
  public/rose-mathematics.html
  script.js
Labels: assigned, gssoc21, level3

#989 Expense tracker
  assets/css/ExpenseTracker.css
  assets/css/studentCalc.css
Labels: gssoc21, level0

#843 Giveaway
  assets/Images/Screenshot (99).png
  assets/Images/giveaway.jpg
  assets/Images/giveawayy.png
  assets/css/giveaway.css
  assets/js/giveaway.js
  public/giveaway.html
  script.js
Labels: assigned, gssoc21, level1

#848 Added Progress Steps JavaScript Project
  assets/GIFs/Progress_steps.gif
  assets/css/Progress_steps.css
  assets/js/Progress_steps.js
  public/Progress_Steps.html
  script.js
Labels: assigned, gssoc21, level2

#973 Digital clock responsiveness #418
  assets/css/digitalClock.css
  assets/js/digitalClock.js
  public/digitalClock.html
  script.js
Labels: gssoc21, level1

#967 Word-Scramble made responsive
  assets/css/wordScramble.css
Labels: gssoc21, level0

#961 UI Updated-Armstrong Checker
  assets/css/ArmstrongNumber.css
  public/ArmstrongNumber.html
Labels: gssoc21, level1

#958 Final Commit
  script.js
Labels: assigned, gssoc21, level0

#864 Adding placeholder in the required fields in contact us section.
  contact.html
Labels: gssoc21, level0

#860 Designed login and signup page
  assets/css/signuplogin.css
  assets/js/signuplogin.js
  contact.html
  index.html
  signuplogin.html
Labels: assigned, gssoc21, level2

#659 currency converter
  assets/GIFs/currencyConverter.gif
  assets/css/currecyConverter.css
  assets/js/currecyConverter.js
  public/currencyConverter.html
  script.js
Labels: assigned, gssoc21, level2

#867 Etch-Sketch
  assets/GIFs/etch_sketch.PNG
  assets/Images/etch-a-sketch.jpg
  assets/js/etch_sketch.js
  public/etch_sketch.html
  script.js
Labels: assigned, gssoc21, level2

#996 Updation of Pinpad
  assets/GIFs/pinpad.gif
  assets/css/pinpad.css
  public/pinpad.html
Labels: assigned, gssoc21, level1

#908 New Project addition : phyllotaxis
  assets/GIFs/avatarMaker-demo.gif
  assets/Images/phyllotaxis.png
  assets/css/phyllotaxis_css/phyllotaxis.min.css
  assets/css/phyllotaxis_css/phyllotaxis.min.css.map
  assets/css/phyllotaxis_css/phyllotaxis.scss
  assets/js/phyllotaxis.js
  assets/sounds/gameOver.mp3
  public/phyllotaxis.html
  script.js
Labels: assigned, gssoc21, level3

#959 Project addition : John Conway's Game of life
  assets/Images/gameOfLife/demo.gif
  assets/Images/gameOfLife/patterns/ants.png
  assets/Images/gameOfLife/patterns/beacon.png
  assets/Images/gameOfLife/patterns/blinker.png
  assets/Images/gameOfLife/patterns/gosper.png
  assets/css/gameOfLIfe_css/gameOfLife.min.css
  assets/css/gameOfLIfe_css/gameOfLife.min.css.map
  assets/css/gameOfLIfe_css/gameOfLife.scss
  assets/js/gameOfLife_js/formations.js
  assets/js/gameOfLife_js/gameOfLife.js
  assets/js/gameOfLife_js/genericFunc.js
  public/gameOfLife.html
  script.js
Labels: gssoc21, level3

#1018 Enhanced the visual of counter
  assets/css/counter.css
  public/counter.html
Labels: gssoc21, level1

#1063 About us Content Improvised
  index.html
Labels: gssoc21, level0

#1013 Fixed GIF image and Toggle Button Bug
  contact.html
  index.html
  projects.html
  script.js
Labels: gssoc21, level1

#697 Quiz app in JS
  assets/Images/quiz/ALPHA.jpg
  assets/Images/quiz/char.jpg
  assets/Images/quiz/demo.png
  assets/Images/quiz/numbers1.jpg
  assets/Images/quiz/pro.jpg
  assets/Images/quiz/resoneing.jpg
  assets/Images/quiz/resoning2.jpg
  assets/Images/quiz/series.jpg
  assets/Images/quiz/series2.jpg
  assets/css/quiz.css
  assets/js/quiz.js
  public/quiz.html
  script.js
Labels: assigned, gssoc21, level2

#1030 Calendar project fix #1002
  assets/Images/calendar_backcover.png
  assets/css/calendar.css
  assets/js/calendar.js
  public/calendar.html
Labels: gssoc21, level1

#1068 background sound is added to simon game
  assets/js/simon.js
  assets/sounds/yellow.mp3
Labels: gssoc21, level1

#1031 gifs is updated of some projects
  assets/GIFs/Text-voice.gif
  assets/GIFs/color-flipper.gif
  assets/GIFs/flappy-bird.gif
  assets/GIFs/textToVoice.gif
  script.js
Labels: gssoc21, level0

#1033 Reset button added - Armstrong Checker project
  assets/css/ArmstrongNumber.css
  assets/js/ArmstrongNumber.js
  public/ArmstrongNumber.html
Labels: gssoc21, level0

#1100 Update README.md
  README.md
Labels: gssoc21, level0

#1097 Project addition : Fractal tree
  assets/Images/fractalTree/demo.png
  assets/Images/fractalTree/fractalTree.gif
  assets/css/fractalTree_css/fractalTree.min.css
  assets/css/fractalTree_css/fractalTree.min.css.map
  assets/css/fractalTree_css/fractalTree.scss
  assets/js/fractalTree_js/fractalTree.js
  public/fractalTree.html
Labels: gssoc21, level2

#900 Document to Handwritting
  assets/Images/page.jpg
  assets/css/DocumenttoHandwrittingcustom.css
  assets/css/DocumenttoHandwrittingdark.css
  assets/fonts/font (0).ttf
  assets/fonts/font (1).ttf
  assets/fonts/font (2).ttf
  assets/fonts/font (3).ttf
  assets/fonts/font (4).ttf
  assets/fonts/font (5).ttf
  assets/fonts/font (6).ttf
  assets/js/DocumenttoHandwrittingscript.js
  assets/js/DocumenttoHandwrittingsketch.js
  assets/pages/page (2).jpg
  public/DocumenttoHandwritting.html
  script.js
Labels: assigned, gssoc21, level3

#1034 Updated_Digital_Fancy_Clock
  assets/GIFs/digitalClock.gif
  assets/Images/digitalClock.jpg
  assets/Images/digitalClockupdated.png
  assets/css/digitalClock.css
  public/digitalClock.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1039 Properly linked the CSS and JS file to the HTML file
  assets/css/ExchangeRate.css
  public/ExchangeRate.html
Labels: gssoc'21, gssoc21, level0

#1108 age calculator updated
  assets/css/AgeCalculator.css
Labels: gssoc21, level0

#1109 harry potter page updated
  assets/css/harry.css
  public/harry.html
Labels: gssoc21, level0

#1059 Note-app updated
  assets/css/noteApp.css
  assets/js/note-app.js
  public/note-app.html
Labels: gssoc21, level1

#1061 Header height changed
  assets/css/styles.css
Labels: gssoc'21, gssoc21, level0

#1062 Update code
  index.html
Labels: gssoc'21, gssoc21, level0

#1069 Modify Todo App project #1001
  assets/GIFs/todo-app.gif
  assets/css/todo-app.css
  assets/js/todo-app.js
  public/todo-app.html
Labels: gssoc'21, gssoc21, level2

#1084 Guess the song!
  assets/Images/guess_song/dark1.jpg
  assets/Images/guess_song/view.png
  assets/css/guess_song.css
  assets/js/guess_song.js
  public/guess_song.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1094 Improving Netflix app
  assets/css/netflix.css
  public/netflix.html
Labels: gssoc'21, gssoc21, level0

#1112 Mouse trails
  assets/GIFs/MouseTrails.gif
  assets/css/MouseTrails.css
  assets/js/MouseTrails.js
  public/MouseTrails.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1045 Deleted duplicate code in index.html and fixed footer (issue- #1043)
  index.html
Labels: gssoc'21, gssoc21, level0

#1095 Successfully added styles and a responsive design to coinToss
  assets/GIFs/coinToss.gif
  assets/Images/game-bg.jpg
  assets/Images/heads.png
  assets/Images/tails.png
  assets/css/Coin-Toss.css
  assets/js/Coin_Toss.js
  public/CoinToss.html
Labels: gssoc'21, gssoc21, level2

#1134 UI of Live Code Editor
  assets/GIFs/LiveEditor.gif
  assets/GIFs/LiveEditor.gif.gif
  assets/css/Live_Code_Editor.css
  assets/js/Live_Code_Editor.js
  public/Live_Code_Editor.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1131 UI of Weight Converter
  assets/GIFs/WeightConverter.gif
  assets/Images/WeightConverter.jpg
  assets/css/WeightConverter.css
  assets/js/WeightConverter.js
  public/WeightConverter.html
Labels: gssoc'21, gssoc21, level1

#1106 Bug fix : multiple entry of projects removed
  .gitignore
  script.js
Labels: gssoc'21, gssoc21, level0

#1133 Ghost text Project
  assets/GIFs/ghost.gif
  assets/css/animatedText.css
  public/Ghost-Text.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1126 rock game updated
  assets/css/rock-paper-scissors.css
  public/Rock-paper-scissor.html
Labels: gssoc'21, gssoc21, level1

#1136 Grocery List Project
  .vscode/settings.json
  assets/GIFs/groceryList.gif
  assets/Images/groceryList.jpg
  assets/css/groceryList.css
  assets/js/groceryList.js
  public/groceryList.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1137 Lorem ipsum generator
  assets/Images/lorem.png
  assets/css/style_lorem.css
  assets/js/lorem_script.js
  public/lorem.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1184 Added the project Music Generator(issue-976)
  assets/Images/music_generator_bg.jpg
  assets/Images/music_generator_ss.jpg
  assets/sounds/bass-drum.wav
  assets/sounds/bugle-first-call.wav
  assets/sounds/chinese-gong.wav
  assets/sounds/drumroll.wav
  assets/sounds/harp.wav
  assets/sounds/military-drum.wav
  public/music_generator.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1117 Project addition : Koch snowflake
  assets/Images/kochSnowflake/demo.png
  assets/css/kochSnowflake_css/kochSnowflake.min.css
  assets/css/kochSnowflake_css/kochSnowflake.min.css.map
  assets/css/kochSnowflake_css/kochSnowflake.scss
  assets/js/kochSnowflake_js/kochSnowflake.js
  public/kochSnowflake.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1132 Adding Colora
  assets/Images/colora.jpg
  assets/Images/colora_favicon.ico
  assets/Images/memeimages/colora.jpg
  assets/css/DiceRoll.css
  assets/css/colora.css
  assets/js/colora.js
  assets/js/jscolor.js
  public/colora.html
  script.js
Labels: gssoc'21, gssoc21, level3

#1139 Updated Whac a Mole game
  assets/css/molegame.css
  assets/js/molegame.js
  public/molegame.html
Labels: gssoc'21, gssoc21, level1

#836 Validated HTML solving issue #708
  assets/css/styles.css
  contact.html
  index.html
  projects.html
Labels: assigned, gssoc21, level1

#742 Created Infinite Scrolling Image Library using Unsplash API #522
  assets/Images/infiniteScroll-loader.svg
  assets/Images/infiniteScroll.png
  assets/css/infiniteScroll.css
  assets/js/infiniteScroll.js
  public/infiniteScroll.html
  script.js
Labels: assigned, gssoc21, level2

#1056 Added new library app project
  assets/GIFs/libraryapp.gif
  assets/css/libraryapp.css
  assets/js/libraryapp.js
  public/libraryapp.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1165 To do app with CRUD and search operation added
  assets/GIFs/todo.gif
  assets/css/todoapp_css/css/bootstrap.min.css
  assets/css/todoapp_css/css/font-awesome.min.css
  assets/css/todoapp_css/css/style.css
  assets/css/todoapp_css/fonts/FontAwesome.otf
  assets/css/todoapp_css/fonts/Roboto-Regular.eot
  assets/css/todoapp_css/fonts/Roboto-Regular.otf
  assets/css/todoapp_css/fonts/Roboto-Regular.svg
  assets/css/todoapp_css/fonts/Roboto-Regular.ttf
  assets/css/todoapp_css/fonts/Roboto-Regular.woff
  assets/css/todoapp_css/fonts/fontawesome-webfont.eot
  assets/css/todoapp_css/fonts/fontawesome-webfont.svg
  assets/css/todoapp_css/fonts/fontawesome-webfont.ttf
  assets/css/todoapp_css/fonts/fontawesome-webfont.woff
  assets/css/todoapp_css/fonts/fontawesome-webfont.woff2
  assets/js/todooapp.js
  public/todoapp.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1170 Added a multiplayer dice game
  assets/Images/dice_it.jfif
  assets/Images/diceit/dice-1.png
  assets/Images/diceit/dice-2.png
  assets/Images/diceit/dice-3.png
  assets/Images/diceit/dice-4.png
  assets/Images/diceit/dice-5.png
  assets/Images/diceit/dice-6.png
  assets/css/diceit.css
  assets/js/diceit.js
  public/diceit.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1173 weather app enhance
  assets/css/Weather_app.css
Labels: gssoc'21, gssoc21, level0

#1177 New Project - Temperature Converter
  assets/GIFs/Temperature_Converter_Backcover.gif
  assets/Images/Temperature_Converter_logo.png
  assets/css/Temperature_Converter.css
  assets/js/Temperature_Converter.js
  public/Temperature_Converter.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1230 library App
  assets/Images/libraryapp.png
  assets/css/libraryapp.css
  assets/js/libraryapp.js
  public/libraryapp.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1172 Add a awesome project(ACE_EYE)
  assets/Images/ACE_EYE.png
  assets/css/ACE_EYE.css
  assets/js/ACE_EYE.js
  public/ACE_EYE.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1243 Validations added to signup/login
  signuplogin.html
Labels: gssoc21, level0

#1194 Removed Merge conflicts pull request #1162 Timeline
  assets/GIFs/timeline.gif
  assets/css/timeline.css
  assets/js/timeline.js
  public/timeline.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1213 Scroll-top added in projects section
  projects.html
Labels: gssoc'21, gssoc21, level1

#1217 Minesweeper game
  assets/GIFs/minesweeper.gif
  assets/css/Minesweeper.css
  assets/js/Minesweeper.js
  public/Minesweeper.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1219 Project addition : Bird loader
  assets/GIFs/birdLoader.gif
  assets/css/birdLoader_scss/birdLoader.min.css
  assets/css/birdLoader_scss/birdLoader.min.css.map
  assets/css/birdLoader_scss/birdLoader.scss
  public/birdLoader.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1220 Project Addition : Purple rain
  assets/Images/purpleRain.gif
  assets/css/purpleRain_css/purpleRain.min.css
  assets/css/purpleRain_css/purpleRain.min.css.map
  assets/css/purpleRain_css/purpleRain.scss
  assets/js/purpleRain_js/purpleRain.js
  public/purpleRain.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1225 Successfully restored the responsiveness of BMI Calculator page
  assets/css/BMICalculator.css
Labels: gssoc'21, gssoc21, level0

#1205 selection sort visualizer in javascript added
  assets/Images/selection-visualizing.png
  assets/css/selectionsort.css
  assets/js/selectionsort.js
  public/selectionsort.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1235 math_trainer app
  assets/Images/math_trainer.png
  assets/css/math_trainer.css
  assets/js/math_trainer.js
  public/MarkDownPreviewer.html
  public/math_trainer.html
  script.js
Labels: gssoc'21, gssoc21, level2
