Repository Vishal-raj-1/Awesome-JavaScript-Projects, pull requests merged in 2021-08, with the labels that each got.

#1910 Drawing App
  assets/Images/Drawing App/Drawing.PNG
  assets/css/Drawing App/style.css
  assets/js/Drawing App/script.js
  public/Drawing App/README.md
  public/Drawing App/index.html
  script.js
Labels: LGMSOC21, 🟥 Level4

#1915 Logo #1810
  assets/Images/Awesome_JavaScript_Logo.png
Labels: LGMSOC21, 🟨 Level2

#1917 Added Random Quote Generator
  assets/Images/Random_Quote_Generator.PNG
  assets/css/Random_Quote_Generator/style.css
  assets/js/Random_Quote_Generator/script.js
  public/Random_Quote_Generator.html
  script.js
Labels: LGMSOC21, 🟧 Level3
