Repository Vishal-raj-1/Awesome-JavaScript-Projects, pull requests merged in 2021-05, with the labels that each got.

#1119 Word Counter Issue solved
  assets/js/wordCounter.js
Labels: gssoc'21, gssoc21, level0

#1178 Added the new breakout game with music and replaced the old one.
  assets/GIFs/breakout.gif
  assets/GIFs/breakout.png
  assets/Images/breakout2.jpg
  assets/css/breakout.css
  assets/js/breakout.js
  assets/sounds/Avengers Notification Tone.mp3
  assets/sounds/Game Over.mp3
  assets/sounds/IOS (Notification).mp3
  public/breakout.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1223 Memory game
  assets/Images/Memory_game/Mind_game.png
  assets/Images/Memory_game/js-badge.svg
  assets/Images/Memory_game/mp3.png
  assets/Images/Memory_game/palm-tree.png
  assets/Images/Memory_game/piggy-bank.png
  assets/Images/Memory_game/plane.png
  assets/Images/Memory_game/ring.png
  assets/Images/Memory_game/robot.png
  assets/Images/Memory_game/shoe.png
  assets/Images/Memory_game/suitcase.png
  assets/css/Memory_game.css
  assets/js/Memory_game.js
  public/Memory_game.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1238 Added amongus minigamee
  assets/GIFs/amongusminigame.gif
  assets/Images/Amongusminigame/dead.png
  assets/Images/Amongusminigame/emb.png
  assets/Images/Amongusminigame/kill.png
  assets/Images/Amongusminigame/logo.png
  assets/Images/Amongusminigame/sabotage.png
  assets/css/Amongusminigame.css
  assets/js/Amongusminigame.js
  assets/sounds/Amongusminigame/amongus.mp3
  assets/sounds/Amongusminigame/kill.mp3
  assets/sounds/Amongusminigame/sabotage.mp3
  public/Amongusminigame.html
  script.js
Labels: gssoc'21, gssoc21, level3

#1241 Xylophone simulator added
  assets/GIFs/Xylophone.gif
  assets/css/Xylophone.css
  assets/js/Xylophone.js
  assets/sounds/note1.wav
  assets/sounds/note2.wav
  assets/sounds/note3.wav
  assets/sounds/note4.wav
  assets/sounds/note5.wav
  assets/sounds/note6.wav
  assets/sounds/note7.wav
  public/Xylophone.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1244 Successfully fixed minor bugs in Student registration form
  assets/css/student.css
  public/student.html
Labels: gssoc'21, gssoc21, level0

#1246 Update drumKit.html
  public/drumKit.html
Labels: gssoc'21, gssoc21, level0

#1251 Fixed the bug Contact
  assets/css/styles.css
  contact.html
Labels: gssoc'21, gssoc21, level0

#1252 improved About page
  assets/css/styles.css
  index.html
Labels: gssoc'21, gssoc21, level0

#1255 Quick sort added
  assets/Images/quick-visualizing.png
  assets/css/quicksort.css
  assets/js/quicksort.js
  public/quicksort.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1256 counting sort added
  assets/Images/counting-visualizing.png
  assets/css/countingsort.css
  assets/js/countingsort.js
  public/countingsort.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1264 3 Github Logo issue
  index.html
Labels: gssoc'21, gssoc21, level0

#1260 Updated Infix Evaluator
  assets/GIFs/Infix-Evaluator-in-JavaScript.png
  assets/Images/Restaurant-image/A.jpg
  assets/Images/Restaurant-image/B.jpg
  assets/Images/Restaurant-image/C.jpg
  assets/Images/Restaurant-image/a.jpg
  assets/Images/Restaurant-image/b.jpg
  assets/Images/Restaurant-image/c.jpg
  assets/Images/bg-infix.jpg
  assets/css/infixevaluator.css
  assets/js/infixevaluator.js
  public/infixevaluator.html
Labels: gssoc'21, gssoc21, level1

#1276 added Reaction Game
  assets/Images/ReactionGame/rg2.jpg
  assets/css/ReactionGame.css
  assets/js/ReactionGame.js
  public/ReactionGame.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1190 Added Error page
  404.html
Labels: gssoc'21, gssoc21, level1

#1193 modify local storage project #942
  assets/GIFs/localstorage.gif
  assets/Images/localstorage.png
  assets/css/localstorage.css
  assets/js/localstorage.js
  public/localstorage.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1248 Add Proxy Pattern Two way Binding and validator Sample
  assets/Images/SimpleTwoWayBindingAndValidator.jpg
  public/SimpleTwoWayBindingAndValidator.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1278 positioning of toggle button
  index.html
Labels: gssoc'21, gssoc21, level0

#1284 contact issue fixed
  contact.html
Labels: gssoc'21, gssoc21, level0

#1285 social media links done
  index.html
  signuplogin.html
Labels: gssoc'21, gssoc21, level0

#1283 Random name generator
  assets/Images/random_name_generator.png
  assets/css/random_name_generator.css
  assets/js/random_name_generator.js
  public/random_name_generator.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1378 px-rem converter added
  assets/GIFs/px-rem.gif
  assets/css/px-rem.css
  assets/js/px-rem.js
  public/px-rem.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1267 Project addition : Coding jokes
  assets/Images/codingJokes.png
  assets/css/codingJokes.css
  assets/js/codingJokes.js
  public/codingJokes.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1298 Changes made "CHESS GAME"
  assets/css/chess.css
  public/chess.html
Labels: gssoc'21, gssoc21, level0

#1387 Added joystick controls project with animations
  assets/GIFs/joystick.gif
  assets/Images/joystick/controls.png
  assets/Images/joystick/head.png
  assets/css/joystick.css
  assets/js/joystick.js
  assets/sounds/joystick/Jump.mp3
  assets/sounds/joystick/inv.mp3
  assets/sounds/joystick/move.mp3
  assets/sounds/joystick/shoot.mp3
  assets/sounds/joystick/water.wav
  public/joystick.html
  script.js
Labels: gssoc'21, gssoc21, level3

#1389 Added RGB TO HEX Converter
  assets/Images/RGB_HEX.png
  assets/css/RGB_HEX.css
  assets/js/RGB_HEX.js
  public/RGB_HEX.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1410 Added project Dinosaur Game
  assets/GIFs/DinosaurGame.gif
  assets/Images/DinosaurGame bg.jpg
  assets/Images/DinosaurGame cactus.png
  assets/Images/DinosaurGame character.webp
  assets/css/DinosaurGame.css
  assets/js/DinosaurGame.js
  public/DinosaurGame.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1424 Corrected the path for background image
  assets/css/infixevaluator.css
Labels: gssoc'21, gssoc21, level0

#1413 Image Puzzle Game
  assets/Images/ImagePuzzle/london-bridge.jpg
  assets/Images/ImagePuzzle/lotus-temple.JPG
  assets/Images/ImagePuzzle/qutub-minar.jpg
  assets/Images/ImagePuzzle/statue-of-liberty.jpg
  assets/Images/ImagePuzzle/taj-mahal.jpg
  assets/Images/imagePuzzleGame.png
  assets/css/imagePuzzleGame.css
  assets/js/imagePuzzleGame.js
  public/imagePuzzleGame.html
  script.js
Labels: gssoc'21, gssoc21, level3

#1430 merge sort visualizer in javascript added
  assets/Images/merge-visualizing.png
  assets/css/mergesort.css
  assets/js/mergesort.js
  public/mergesort.html
  script.js
Labels: gssoc'21, gssoc21, level0

#1394 added tip calculator project
  assets/Images/tip-calc.png
  assets/css/tip-calc.css
  assets/js/tip-calc.js
  public/tip-calculator.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1402 Battery Indicator
  assets/Images/BatteryIndicator.PNG
  assets/css/BatteryIndicator.css
  assets/js/BatteryIndicator.js
  public/BatteryIndicator.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1395 Button generator Project
  assets/Images/button.PNG
  assets/css/ButtonGenerator.css
  assets/js/ButtonGenerator.js
  public/ButtonGenerator.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1426 PainoApp
  assets/Images/pianoApp.png
  assets/css/pianoApp.css
  assets/js/pianoApp.js
  public/pianoApp.html
Labels: gssoc'21, gssoc21, level0

#1412 3D Image Gallery
  assets/Images/3DImageGallery.PNG
  assets/Images/3DImageGallery/img1.jpg
  assets/Images/3DImageGallery/img2.jpg
  assets/Images/3DImageGallery/img3.jpg
  assets/Images/3DImageGallery/img4.jpg
  assets/Images/3DImageGallery/img5.jpg
  assets/Images/3DImageGallery/img6.jpg
  assets/Images/3DImageGallery/img7.jpg
  assets/Images/3DImageGallery/img8.jpg
  assets/css/3DImageGallery.css
  public/3DImageGallery.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1435 Mortgage Loan Calculator
  assets/Images/mortgage_loan_calculator.png
  assets/css/mortgage_loan_calculator.css
  assets/js/mortgage_loan_calculator.js
  public/mortgage_loan_calculator.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1454 Glittering Background animation
  assets/Images/Glittering_background.png
  assets/js/glittering_background_animation.js
  public/glittering_background_animation.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1503 Project addition : Caesar cipher
  assets/Images/caesarCipher.png
  assets/css/caesarCipher.css
  assets/js/caesarCipher.js
  public/caesarCipher.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1508 Project addition: Bridge N Torch
  assets/Images/bridgeNtorch.png
  assets/css/bridgeNtorch.css
  assets/js/bridgeNtorch.js
  public/bridgeNtorch.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1525 Palindrome checker updated
  assets/Images/palindrome/bg1.jpg
  assets/Images/palindrome/bg11.jpg
  assets/css/palindrome.css
  assets/js/palindrome.js
  public/palindrome.html
Labels: gssoc'21, gssoc21, level1

#1538 Removed Duplicates
  script.js
Labels: gssoc'21, gssoc21, level0

#1433 Added Match_Four_Game
  assets/Images/Match_Four_Game.png
  assets/css/Match_Four_Game.css
  assets/js/Match_Four_Game.js
  public/Match_Four_Game.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1319 Footer changed of home page
  index.html
Labels: gssoc'21, gssoc21, level0

#1539 Vertical timeline
  assets/Images/vertical_timeline/Screenshot.png
  assets/Images/vertical_timeline/cd-icon-location.svg
  assets/Images/vertical_timeline/cd-icon-movie.svg
  assets/Images/vertical_timeline/cd-icon-picture.svg
  assets/css/vertical_timeline/style.css
  assets/css/vertical_timeline/style.scss
  assets/js/vertical_timeline.js
  public/vertical_timeline.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1540 Added Weather App
  assets/Images/weatherApp/Clear.svg
  assets/Images/weatherApp/Clouds.svg
  assets/Images/weatherApp/Drizzle.svg
  assets/Images/weatherApp/Dust.svg
  assets/Images/weatherApp/Fog.svg
  assets/Images/weatherApp/Haze.svg
  assets/Images/weatherApp/Image.PNG
  assets/Images/weatherApp/Mist.svg
  assets/Images/weatherApp/Rain.svg
  assets/Images/weatherApp/Smoke.svg
  assets/Images/weatherApp/Snow.svg
  assets/Images/weatherApp/Thunderstorm.svg
  assets/Images/weatherApp/earth.svg
  assets/Images/weatherApp/error.svg
  assets/Images/weatherApp/loading.svg
  assets/Images/weatherApp/not-found.svg
  assets/Images/weatherApp/placeholder.svg
  assets/css/weatherApp.css
  assets/js/weatherApp.js
  public/weatherApp.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1544 FullScreen functionality
  assets/Images/Fullscreen.png
  assets/js/fullscreen.js
  public/fullscreen.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1552 World Clock
  assets/Images/worldclock/bg.png
  assets/Images/worldclock/day.jpg
  assets/Images/worldclock/dusk.jpg
  assets/Images/worldclock/night.jpg
  assets/Images/worldtime.png
  assets/css/worldclock.css
  assets/js/worldclock.js
  public/worldclock.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1562 Added the project Decimal to binary converter
  assets/GIFs/DecimalToBinaryConverter.gif
  assets/css/DecimalToBinaryConverter.css
  public/DecimalToBinaryConverter.html
  script.js
Labels: gssoc'21, gssoc21, level1

#1563 adding energy converter
  assets/Images/energy-converter.jpg
  public/energy-converter.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1571 Scientific Calculator
  assets/Images/Calculator.png
  assets/css/calculator.css
  assets/js/calculator.js
  public/calculator.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1555 Filterable Image Gallery
  assets/Images/Filterable_Image_Gallery/Filterable_Image_Gallery.png
  assets/Images/Filterable_Image_Gallery/camera1.jpg
  assets/Images/Filterable_Image_Gallery/camera2.jpg
  assets/Images/Filterable_Image_Gallery/camera3.jpg
  assets/Images/Filterable_Image_Gallery/camera4.jpg
  assets/Images/Filterable_Image_Gallery/camera5.jpg
  assets/Images/Filterable_Image_Gallery/headphone1.jpg
  assets/Images/Filterable_Image_Gallery/headphone2.jpg
  assets/Images/Filterable_Image_Gallery/headphone3.jpg
  assets/Images/Filterable_Image_Gallery/headphone4.jpg
  assets/Images/Filterable_Image_Gallery/headphone5.jpg
  assets/Images/Filterable_Image_Gallery/headphone6.jpg
  assets/Images/Filterable_Image_Gallery/headphone7.jpg
  assets/Images/Filterable_Image_Gallery/mobile1.jpg
  assets/Images/Filterable_Image_Gallery/mobile2.jpg
  assets/Images/Filterable_Image_Gallery/mobile3.jpg
  assets/Images/Filterable_Image_Gallery/mobile4.jpg
  assets/Images/Filterable_Image_Gallery/mobile5.jpg
  assets/Images/Filterable_Image_Gallery/mobile6.jpg
  assets/Images/Filterable_Image_Gallery/shoe1.jpg
  assets/Images/Filterable_Image_Gallery/shoe2.jpg
  assets/Images/Filterable_Image_Gallery/shoe3.jpg
  assets/Images/Filterable_Image_Gallery/shoe4.jpg
  assets/Images/Filterable_Image_Gallery/watch1.jpg
  assets/Images/Filterable_Image_Gallery/watch2.jpg
  assets/Images/Filterable_Image_Gallery/watch3.jpg
  assets/Images/Filterable_Image_Gallery/watch4.jpg
  assets/Images/Filterable_Image_Gallery/watch5.jpg
  assets/Images/Filterable_Image_Gallery/watch6.jpg
  assets/css/Filterable_Image_Gallery.css
  assets/js/Filterable_Image_Gallery.js
  public/Filterable_Image_Gallery.html
  script.js
Labels: gssoc'21, gssoc21, level2

#226 Insect Catch Game
  assets/Images/Insect Catch.png
  assets/css/InsectCatch.css
  assets/js/InsectCatch.js
  public/InsectCatch.html
  script.js
Labels: assigned, gssoc21, level2

#673 Add Dice Game
  assets/GIFs/dice_game.gif
  assets/Images/dice1.png
  assets/Images/dice2.png
  assets/Images/dice3.png
  assets/Images/dice4.png
  assets/Images/dice5.png
  assets/Images/dice6.png
  assets/Images/favicons/FF.ico
  assets/Images/images/dice1.png
  assets/Images/images/dice2.png
  assets/Images/images/dice3.png
  assets/Images/images/dice4.png
  assets/Images/images/dice5.png
  assets/Images/images/dice6.png
  assets/css/dice_game.css
  assets/js/dice_game.js
  public/dice_game.html
  script.js
Labels: assigned, gssoc21, level2

#1701 3D cube oribit controls
  assets/js/3DCube.js
  public/3DCube.html
Labels: gssoc21, level2

#1718 completed issue 920
  assets/GIFs/WebDevelopmentCourse.gif
  assets/Images/WebDevelopmentCoursebackground.jpg
  assets/css/WebDevelopmentCourse.css
  assets/js/WebDevelopmentCourse.js
  public/WebDevelopmentCourse.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1566 Added Animated Unsubscribe Page
  assets/GIFs/unsub_page.png
  assets/css/unsub_page.css
  assets/js/unsub_page.js
  public/unsub_page.html
  script.js
Labels: gssoc'21, gssoc21, level2

#1766 Random_Picker_visualiser #1762
  assets/GIFs/README.md
  assets/css/Random_picker/Random_Picker.css
  assets/js/Random_Picker.js
  public/Random_Picker.html
  script.js
Labels: gssoc21, level2

#1757 Piano
  assets/sounds/notes/A.mp3
  assets/sounds/notes/Ab.mp3
  assets/sounds/notes/B.mp3
  assets/sounds/notes/Bb.mp3
  assets/sounds/notes/C.mp3
  assets/sounds/notes/D.mp3
  assets/sounds/notes/Db.mp3
  assets/sounds/notes/E.mp3
  assets/sounds/notes/Eb.mp3
  assets/sounds/notes/F.mp3
  assets/sounds/notes/G.mp3
  assets/sounds/notes/Gb.mp3
  public/joke_generator.html
  public/number_facts.html
  public/piano.html
  public/qoute.html
Labels: gssoc21, level2

#1226 Adding Logo
  Logo.png
Labels: gssoc21, level1

#1523 Handcricket
  assets/GIFs/handcricket.gif
  assets/css/handcricket.css
  assets/js/handcricket.js
  public/handcricket.html
  script.js
Labels: gssoc21, level2

#1732 Compressed game mod
  assets/GIFs/among.gif
  assets/Images/amongus/among-us-logo.jpg
  assets/Images/amongus/back.jpg
  assets/Images/amongus/banner.png
  assets/Images/amongus/dead.png
  assets/Images/amongus/demo.svg
  assets/Images/amongus/emb.png
  assets/Images/amongus/kill.png
  assets/Images/amongus/logo.png
  assets/Images/amongus/sabotage.png
  assets/css/amongus/amongus.css
  assets/css/amongus/style.css
  assets/css/amongus/style2.css
  assets/css/amongus/style3.css
  assets/js/amongus/amongus.js
  assets/js/amongus/index.js
  assets/js/amongus/index2.js
  assets/sounds/amongus/amongmain.mp3
  assets/sounds/amongus/amongus.mp3
  assets/sounds/amongus/enter.mp3
  assets/sounds/amongus/kill.mp3
  assets/sounds/amongus/sabotage.mp3
  public/amongus/amongus.html
  public/amongus/amongusmove.html
  public/amongus/gamemain.html
  public/amongus/index.html
  script.js
Labels: gssoc21, level2

#1729 Active link feature added
  contact.html
  index.html
  projects.html
Labels: gssoc21, level1

#1583 Added Photo Details teller project
  assets/Images/photoDetails.png
  assets/Images/pisces.png
  assets/Images/sagi.png
  assets/Images/scorpio.png
  public/photoDetails.html
  script.js
Labels: gssoc21, level1

#1590 Form Validator Project updated
  assets/Images/formValidate.png
  assets/Images/formvalidate.png
  assets/css/formValidate.css
  assets/js/formValidate.js
  public/formvalidate.html
  script.js
Labels: gssoc21, level2

#1627 More Conversion(Colors) are added
  assets/css/Dynamicquotegenerator.css
  assets/js/Dynamicquotegenerator.js
  public/Dynamic-quotegenerator.html
Labels: gssoc21, level2

#1629 added Line through effect
  assets/Images/line-through.png
  assets/css/line-through.css
  assets/js/line-through.js
  public/line_through.html
  script.js
Labels: gssoc21, level2

#1771 Random Choice Picker
  assets/Images/random_choice_picker.png
  assets/css/random_choice_picker.css
  assets/js/random_choice_picker.js
  public/random_choice_picker.html
  script.js
Labels: gssoc21, level1

#1499 added ludo game
  assets/Images/ludo/1.jpg
  assets/Images/ludo/2.jpg
  assets/Images/ludo/3.jpg
  assets/Images/ludo/4.jpg
  assets/Images/ludo/5.jpg
  assets/Images/ludo/6.jpg
  assets/Images/ludo/board.gif
  assets/Images/ludo/dice.gif
  assets/Images/ludo/ludo.png.png
  assets/js/ludo.js
  public/ludo.html
  script.js
Labels: gssoc'21, gssoc21

#350 Added Filter_Search in Awesome-JavaScript-Projects/public
  assets/css/filter_search.css
  assets/js/filter_search.js
  public/Filter_Search.html
  public/filter_search.html
  script.js
Labels: assigned, gssoc21, level2
