Repository Vishal-raj-1/Awesome-JavaScript-Projects, pull requests merged in 2021-07, with the labels that each got.

#1884 Removed Duplicates
  script.js
Labels: LGMSOC21, 🟧 Level3

#1887 removed the bug which causes redirecting to blank page.
  public/Restaurant.html
Labels: LGMSOC21, 🟨 Level2

#1890 feat: add scatter chart app
  assets/Images/scatter_chart.png
  assets/css/scatter_chart.css
  assets/js/scatter_chart.js
  public/scatter_chart.html
  script.js
Labels: LGMSOC21, 🟥 Level4

#1888 Bar Chart added
  assets/Images/barchart.png
  public/barchart.html
  script.js
Labels: LGMSOC21, 🟥 Level4

#1903 Expand and collapse card
  assets/css/FAQs.css
  public/FAQs.html
Labels: LGMSOC21, 🟨 Level2
