Repository Vishal-raj-1/Awesome-JavaScript-Projects, pull requests merged in 2021-03, with the labels that each got.

#419 Contacts Search
  assets/GIFs/contactSearch.gif
  assets/js/ContactSearch.js
  public/contactSearch.html
  script.js
Labels: gssoc21, level2

#273 UserListFilter project added
  assets/GIFs/UserListFilter.gif
  assets/css/UserListFilter.css
  assets/js/UserListFilter.js
  public/UserListFilter.html
  script.js
Labels: gssoc'21, level2

#379 Note app styling
  assets/GIFs/noteApp.gif
  assets/css/noteApp.css
  assets/js/note-app.js
  public/note-app.html
Labels: gssoc'21, level2

#447 Added Color Picker Converter
  assets/GIFs/ColorPickerConverter.gif
  assets/Images/favicons/ColorPickerConverter.png
  assets/css/ColorPickerConverter.css
  assets/js/ColorPickerConverter.js
  public/ColorPickerConverter.html
  script.js
Labels: gssoc'21, level3

#370 Device info
  assets/GIFs/DeviceInfo.gif
  assets/Images/deviceInfo.png
  assets/css/deviceInfo.css
  assets/js/deviceInfo.js
  public/deviceInfo.html
  script.js
Labels: gssoc'21, level3

#528 PIN code search
  assets/GIFs/pinCodeSearch.gif
  assets/css/pinCodeSearch.css
  assets/js/PinCodeSearch.js
  public/pinCodeSearch.html
  script.js
Labels: gssoc'21, level2

#580 Fixed Issue number #573 (Collapse Plugin not working under Navbar section in lower screen dimension)
  index.html
Labels: gssoc'21, level1

#622 Word Scramble game
  assets/GIFs/wordScramble.gif
  assets/css/wordScramble.css
  assets/js/wordScramble.js
  index.html
  public/wordScramble.html
  script.js
Labels: assigned, gssoc21, level3

#623 new questions and random question pick feature added
  assets/css/quizapp.css
  assets/js/quizapp.js
  public/quizapp.html
Labels: gssoc21

#383 Added the code for RGB Color Guessing Game[GSSoC'21]
  RGB Color.css
  assets/GIFs/RGB_Color.gif
  assets/css/RGB_Color.css
  assets/js/RGB_Color.js
  public/RGB_Color_Guessing_Game.html
  script.js
Labels: gssoc21, level2

#449 Maths Quiz Game #302
  assets/GIFs/MathQuiz.gif
  assets/Images/MathQuiz.jpg
  assets/css/MathQuiz.css
  assets/js/MathQuiz.js
  public/MathQuiz.html
  script.js
Labels: gssoc21, level2

#406 Added Download button
  assets/js/draw.js
  public/draw.html
Labels: gssoc21, level2

#710 Added Pagination Project
  assets/Images/Pagination.png
  assets/css/Pagination.css
  assets/js/Pagination.js
  public/Pagination.html
  script.js
Labels: gssoc21, level2
